### ISSUE TITLE
make command to get tags

### ISSUE THREAD

**Issue by lilggamegenius** [golgi-apparatus/aqua#9]
make something like ?tags to get tags of a link or id

**Comment by golgi-apparatus** [comment]
make ?tag with noargs return the tags for the previously linked gelbooru post

**Comment by golgi-apparatus** [comment]
from readme.md 2016/07/07 22:33 PDT

`?tags <id>         return the tags for the specified gelbooru id. if id is blank, returns the tags for the previously linked image`

**Comment by golgi-apparatus** [comment]
https://github.com/golgi-apparatus/aqua/commit/d88d7e81f14c0445eeb5b7323cee8a3a14c09471 here is the update
